import { Component } from '@angular/core';

@Component({
  selector: 'app-volunteers-list',
  templateUrl: './volunteers-list.component.html',
  styleUrls: ['./volunteers-list.component.scss'],
})
export class VolunteersListComponent {
  Volunteers: any = [
    {
      id: 1,
      name: 'Məmmədova Aydan Elçin qızı',
      work_status: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      date_of_birth: '08.10.2022',
      fin: '18VHOST',
      date_of_place: 'Azərbaycan, Bərdə',
      marital_status: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
      mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'] ,
      phone: 'Yoxdur',
    },
    {
      id: 2,
      name: 'Səttarova Ayşən Arzu qızı',
      work_status: 'Gözləyir',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      date_of_birth: '08.10.2022',
      fin: '18VHOST',
      date_of_place: 'Azərbaycan, Bərdə',
      marital_status: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: '',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
        mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
        mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'] ,
      phone: 'Yoxdur',
    },
    {
      id: 3,
      name: 'Məmmədova Aynura Aftandil qızı',
      work_status: 'Keçməyib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      date_of_birth: '08.10.2022',
      fin: '18VHOST',
      date_of_place: 'Azərbaycan, Bərdə',
      marital_status: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
        mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
        mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'] ,
      phone: 'Yoxdur',
    },
    {
      id: 4,
      name: 'Məmmədova Aydan Elçin qızı',
      work_status: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      date_of_birth: '08.10.2022',
      fin: '18VHOST',
      date_of_place: 'Azərbaycan, Bərdə',
      marital_status: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        '',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
        mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
        mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'] ,
      phone: 'Yoxdur',
    },
    {
      id: 5,
      name: 'Səttarova Ayşən Arzu qızı',
      work_status: 'Gözləyir',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      date_of_birth: '08.10.2022',
      fin: '18VHOST',
      date_of_place: 'Azərbaycan, Bərdə',
      marital_status: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        '',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
        mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
        mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'] ,
      phone: 'Yoxdur',
    },
    {
      id: 6,
      name: 'Məmmədova Aydan Elçin qızı',
      work_status: 'Gözləyir',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      date_of_birth: '08.10.2022',
      fin: '18VHOST',
      date_of_place: 'Azərbaycan, Bərdə',
      marital_status: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
        mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
        mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'] ,
      phone: 'Yoxdur',
    },
    {
      id: 7,
      name: 'Şəmmədli Aysun Vüqar qızı',
      work_status: 'Keçməyib',
      status: 'Passiv könüllü',
      gender: 'Qadın',
      date_of_birth: '08.10.2022',
      fin: '18VHOST',
      date_of_place: 'Azərbaycan, Bərdə',
      marital_status: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
        mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'] ,
      phone: 'Yoxdur',
    },
    {
      id: 8,
      name: 'Məmmədova Aynura Aftandil qızı',
      work_status: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      date_of_birth: '08.10.2022',
      fin: '18VHOST',
      date_of_place: 'Azərbaycan, Bərdə',
      marital_status: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
        mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
        mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'] ,
      phone: 'Yoxdur',
    },
    {
      id: 9,
      name: 'Məmmədova Aydan Elçin qızı',
      work_status: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      date_of_birth: '08.10.2022',
      fin: '18VHOST',
      date_of_place: 'Azərbaycan, Bərdə',
      marital_status: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
        mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
        mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'] ,
      phone: 'Yoxdur',
    },
    {
      id: 10,
      name: 'Şəmmədli Aysun Vüqar qızı',
      work_status: 'Gözləyir',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      date_of_birth: '08.10.2022',
      fin: '18VHOST',
      date_of_place: 'Azərbaycan, Bərdə',
      marital_status: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
        mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
        mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'] ,
      phone: 'Yoxdur',
    },
    {
      id: 11,
      name: 'Məmmədova Aydan Elçin qızı',
      work_status: 'Gözləyir',
      status: 'Passiv könüllü',
      gender: 'Qadın',
      date_of_birth: '08.10.2022',
      fin: '18VHOST',
      date_of_place: 'Azərbaycan, Bərdə',
      marital_status: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
        mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
        mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'] ,
      phone: 'Yoxdur',
    },
    {
      id: 12,
      name: 'Şəmmədli Aysun Vüqar qızı',
      work_status: 'Keçib',
      status: 'Passiv könüllü',
      gender: 'Qadın',
      date_of_birth: '08.10.2022',
      fin: '18VHOST',
      date_of_place: 'Azərbaycan, Bərdə',
      marital_status: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
        mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
        mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'] ,
      phone: 'Yoxdur',
    },
    {
      id: 13,
      name: 'Məmmədova Aynura Aftandil qızı',
      work_status: 'Keçməyib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      date_of_birth: '08.10.2022',
      fin: '18VHOST',
      date_of_place: 'Azərbaycan, Bərdə',
      marital_status: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
        mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
        mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'] ,
      phone: 'Yoxdur',
    },
    {
      id: 14,
      name: 'Şəmmədli Aysun Vüqar qızı',
      work_status: 'Keçməyib',
      status: 'Passiv könüllü',
      gender: 'Qadın',
      date_of_birth: '08.10.2022',
      fin: '18VHOST',
      date_of_place: 'Azərbaycan, Bərdə',
      marital_status: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardımç ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
        mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
        mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'] ,
      phone: 'Yoxdur',
    },
    {
      id: 15,
      name: 'Məmmədova Aydan Elçin qızı',
      work_status: 'Gözləyir',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      date_of_birth: '08.10.2022',
      fin: '18VHOST',
      date_of_place: 'Azərbaycan, Bərdə',
      marital_status: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardımç ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
        mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
        mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'] ,
      phone: 'Yoxdur',
    },
    // {
    //   id: 16,
    //   name: 'Məmmədova Aynura Aftandil qızı',
    //   work_status: 'Gözləyir',
    //   status: 'Passiv könüllü',
    //   gender: 'Qadın',
    //   date_of_birth: '08.10.2022',
    //   fin: '18VHOST',
    //   date_of_place: 'Azərbaycan, Bərdə',
    //   marital_status: 'Subay',
    //   nationality: 'Azərbaycanlı',
    //   citizenship: 'Azərbaycan',
    //   idCardNumber: 'AZE 17881647',
    //   idCardGiveDate: '16.10.2018',
    //   idCardGivePlace: 'Nizami RPŞ',
    //   registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
    //   actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
    //   idCardCopy: 'id.png',
    //   photo: 'photo.png',
    //   cv: 'cv.docx',
    //   generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
    //   occupationEduStep: 'yoxdur',
    //   higherEducationStep: 'Bakalavriat',
    //   uniCourse: '4-cü kurs',
    //   higherEducationPlaceNameAndDate:
    //     'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
    //   facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
    //   diplomaGiveDate: 'Yoxdur',
    //   courseAndEvents: [
    //     '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
    //     '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
    //     '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
    //     '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
    //     '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
    //   ],
    //   workStatus: 'İşləmir',
    //   workPlacePositionStaj: 'Yoxdur',
    //   volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
    //   volunteersAreaAndPeriod:
    //     'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
    //   volunteersInterestArea:
    //     'Ilk yardımç ilkin psixoloji yardım, maarifləndirmə',
    //   fhnAim:
    //     'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
    //   mail: 'amamedova679@gmail.com',
    //   mobilePhone: '+994 50 654 07 51',
    //   phone: 'Yoxdur',
    // },
    // {
    //   id: 17,
    //   name: 'Məmmədova Aynura Aftandil qızı',
    //   work_status: 'Gözləyir',
    //   status: 'Passiv könüllü',
    //   gender: 'Qadın',
    //   date_of_birth: '08.10.2022',
    //   fin: '18VHOST',
    //   date_of_place: 'Azərbaycan, Bərdə',
    //   marital_status: 'Subay',
    //   nationality: 'Azərbaycanlı',
    //   citizenship: 'Azərbaycan',
    //   idCardNumber: 'AZE 17881647',
    //   idCardGiveDate: '16.10.2018',
    //   idCardGivePlace: 'Nizami RPŞ',
    //   registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
    //   actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
    //   idCardCopy: 'id.png',
    //   photo: 'photo.png',
    //   cv: 'cv.docx',
    //   generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
    //   occupationEduStep: 'yoxdur',
    //   higherEducationStep: 'Bakalavriat',
    //   uniCourse: '4-cü kurs',
    //   higherEducationPlaceNameAndDate:
    //     'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
    //   facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
    //   diplomaGiveDate: 'Yoxdur',
    //   courseAndEvents: [
    //     '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
    //     '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
    //     '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
    //     '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
    //     '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
    //   ],
    //   workStatus: 'İşləmir',
    //   workPlacePositionStaj: 'Yoxdur',
    //   volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
    //   volunteersAreaAndPeriod:
    //     'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
    //   volunteersInterestArea:
    //     'Ilk yardımç ilkin psixoloji yardım, maarifləndirmə',
    //   fhnAim:
    //     'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
    //   mail: 'amamedova679@gmail.com',
    //   mobilePhone: '+994 50 654 07 51',
    //   phone: 'Yoxdur',
    // }
  ];
  // getInnerObjectEntries() {
  //   return Object.entries(this.Volunteers.langSkills);
  // }
}



