import { Component } from '@angular/core';
import { FormBuilder, FormGroup, FormArray,Validators } from '@angular/forms';

@Component({
  selector: 'app-volunteers-list',
  templateUrl: './volunteers-list.component.html',
  styleUrls: ['./volunteers-list.component.scss'],
})
export class VolunteersListComponent{
  work_status: any = ['Keçib', 'Keçməyib', 'Gözləyir'];
  gender: any = ['Kişi', 'Qadın'];
  Volunteers: any = [
    {
      id: 1,
      name: 'Məmmədova Aydan Elçin qızı',
      workingStatus: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      dateOfBirth: '08.10.2022',
      fin: '18VHOST',
      dateOfPlace: 'Azərbaycan, Bərdə',
      maritalStatus: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
      mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'],
      phone: 'Yoxdur',
    },
    {
      id: 2,
      name: 'Səttarova Ayşən Arzu qızı',
      workingStatus: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      dateOfBirth: '08.10.2022',
      fin: '18VHOST',
      dateOfPlace: 'Azərbaycan, Bərdə',
      maritalStatus: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
      mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'],
      phone: 'Yoxdur',
    },
    {
      id: 3,
      name: 'Məmmədova Aynura Aftandil qızı',
      workingStatus: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      dateOfBirth: '08.10.2022',
      fin: '18VHOST',
      dateOfPlace: 'Azərbaycan, Bərdə',
      maritalStatus: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
      mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'],
      phone: 'Yoxdur',
    },
    {
      id: 4,
      name: 'Məmmədova Aydan Elçin qızı',
      workingStatus: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      dateOfBirth: '08.10.2022',
      fin: '18VHOST',
      dateOfPlace: 'Azərbaycan, Bərdə',
      maritalStatus: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
      mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'],
      phone: 'Yoxdur',
    },
    {
      id: 5,
      name: 'Səttarova Ayşən Arzu qızı',
      workingStatus: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      dateOfBirth: '08.10.2022',
      fin: '18VHOST',
      dateOfPlace: 'Azərbaycan, Bərdə',
      maritalStatus: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
      mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'],
      phone: 'Yoxdur',
    },
    {
      id: 6,
      name: 'Məmmədova Aydan Elçin qızı',
      workingStatus: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      dateOfBirth: '08.10.2022',
      fin: '18VHOST',
      dateOfPlace: 'Azərbaycan, Bərdə',
      maritalStatus: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
      mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'],
      phone: 'Yoxdur',
    },
    {
      id: 7,
      name: 'Şəmmədli Aysun Vüqar qızı',
      workingStatus: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      dateOfBirth: '08.10.2022',
      fin: '18VHOST',
      dateOfPlace: 'Azərbaycan, Bərdə',
      maritalStatus: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
      mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'],
      phone: 'Yoxdur',
    },
    {
      id: 8,
      name: 'Məmmədova Aynura Aftandil qızı',
      workingStatus: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      dateOfBirth: '08.10.2022',
      fin: '18VHOST',
      dateOfPlace: 'Azərbaycan, Bərdə',
      maritalStatus: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
      mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'],
      phone: 'Yoxdur',
    },
    {
      id: 9,
      name: 'Məmmədova Aydan Elçin qızı',
      workingStatus: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      dateOfBirth: '08.10.2022',
      fin: '18VHOST',
      dateOfPlace: 'Azərbaycan, Bərdə',
      maritalStatus: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
      mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'],
      phone: 'Yoxdur',
    },
    {
      id: 10,
      name: 'Şəmmədli Aysun Vüqar qızı',
      workingStatus: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      dateOfBirth: '08.10.2022',
      fin: '18VHOST',
      dateOfPlace: 'Azərbaycan, Bərdə',
      maritalStatus: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
      mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'],
      phone: 'Yoxdur',
    },
    {
      id: 11,
      name: 'Məmmədova Aydan Elçin qızı',
      workingStatus: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      dateOfBirth: '08.10.2022',
      fin: '18VHOST',
      dateOfPlace: 'Azərbaycan, Bərdə',
      maritalStatus: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
      mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'],
      phone: 'Yoxdur',
    },
    {
      id: 12,
      name: 'Şəmmədli Aysun Vüqar qızı',
      workingStatus: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      dateOfBirth: '08.10.2022',
      fin: '18VHOST',
      dateOfPlace: 'Azərbaycan, Bərdə',
      maritalStatus: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
      mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'],
      phone: 'Yoxdur',
    },
    {
      id: 13,
      name: 'Məmmədova Aynura Aftandil qızı',
      workingStatus: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      dateOfBirth: '08.10.2022',
      fin: '18VHOST',
      dateOfPlace: 'Azərbaycan, Bərdə',
      maritalStatus: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
      mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'],
      phone: 'Yoxdur',
    },
    {
      id: 14,
      name: 'Şəmmədli Aysun Vüqar qızı',
      workingStatus: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      dateOfBirth: '08.10.2022',
      fin: '18VHOST',
      dateOfPlace: 'Azərbaycan, Bərdə',
      maritalStatus: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
      mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'],
      phone: 'Yoxdur',
    },
    {
      id: 15,
      name: 'Məmmədova Aydan Elçin qızı',
      workingStatus: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      dateOfBirth: '08.10.2022',
      fin: '18VHOST',
      dateOfPlace: 'Azərbaycan, Bərdə',
      maritalStatus: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
      mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'],
      phone: 'Yoxdur',
    },
    {
      id: 16,
      name: 'Məmmədova Aynura Aftandil qızı',
      workingStatus: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      dateOfBirth: '08.10.2022',
      fin: '18VHOST',
      dateOfPlace: 'Azərbaycan, Bərdə',
      maritalStatus: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
      mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'],
      phone: 'Yoxdur',
    },
    {
      id: 17,
      name: 'Məmmədova Aynura Aftandil qızı',
      workingStatus: 'Keçib',
      status: 'Aktiv könüllü',
      gender: 'Qadın',
      dateOfBirth: '08.10.2022',
      fin: '18VHOST',
      dateOfPlace: 'Azərbaycan, Bərdə',
      maritalStatus: 'Subay',
      nationality: 'Azərbaycanlı',
      citizenship: 'Azərbaycan',
      idCardNumber: 'AZE 17881647',
      idCardGiveDate: '16.10.2018',
      idCardGivePlace: 'Nizami RPŞ',
      registeredAddress: 'Nizami ray.,Ş.Mirzəyev 56., mən.1',
      actualAddress: 'Sabunçu ray., M.Fətəliyev 80., mən. 1',
      idCardCopy: 'id.png',
      photo: 'photo.png',
      cv: 'cv.docx',
      generalEducationStep: 'Nizami rayonu, 238 saylı tam orta məktəb, 2016',
      occupationEduStep: 'yoxdur',
      higherEducationStep: 'Bakalavriat',
      uniCourse: '4-cü kurs',
      higherEducationPlaceNameAndDate:
        'Azərbaycan Dövlət Neft və Sənaye universiteti, 2016',
      facultySpeciality: 'İnformasiya texnologiyaları, Komputer Elmləri',
      diplomaGiveDate: 'Yoxdur',
      courseAndEvents: [
        '1.Introduction to Psychology. Yale University, online course, Coursera - 08.10.2022',
        '2.Start up Son-Rise program, ILBS, Azerbaijan - 18.05.2022- 18.09.2022',
        '3.Solution-focused therapy, online course, Udemy- 30.09.2022',
        '4.Attachment styles approach in marriage and relationship, online course, Udemy -28.08.2022',
        '5.Criminology and Criminal Psychology/ certified CSI+ course, Udemy - 27.08.2022',
      ],
      workStatus: 'İşləmir',
      workPlacePositionStaj: 'Yoxdur',
      volunteersInfo: '"Bakı Şəhər Halqası" Könüllüləri',
      volunteersAreaAndPeriod:
        'Mineps 7 Qlobal İdman Konfransı - CCW, 26-29 iyun, 2023',
      volunteersInterestArea:
        'Ilk yardım, ilkin psixoloji yardım, maarifləndirmə',
      fhnAim:
        'Könüllülük proqramına qoşularaq gələcəyin psixoloqu olaraq fövqəladə hallarda ilkin psixoloji yardım haqqında maariflənmək və bunu praktikada tətbiq etmək istəyirəm. Təkcə psixoloq olaraq yox, həm də bir vətəndaş kimi ilkin yardım və ilkin psixoloji yardımın incəliklərini öyrənmək istəyirəm.',
      mail: ['amamedova679@gmail.com', 'amamedova679@gmail.com'],
      mobilePhone: ['+994 50 654 07 51', '+994 50 654 07 51'],
      phone: 'Yoxdur',
    },
  ];
  isSidebarOpen = false;
  toggleSidebar() {
    this.isSidebarOpen = !this.isSidebarOpen;
  }

  filterForm: FormGroup;
  constructor(private fb: FormBuilder) {
    this.filterForm = this.fb.group({
      search: ['', Validators.required],
      applyDate: ['', Validators.required],
      gender: ['', Validators.required],
      dateOfBirth: ['', Validators.required],
      citizenship: ['', Validators.required],
      registeredAddress: ['', Validators.required],
      actualAddress: ['', Validators.required],
      workPractise: ['', Validators.required],
      higherEducationStep: ['', Validators.required],
      uniCourse: ['', Validators.required],
      applyResult: ['', Validators.required],
      langSkills: ['', Validators.required],
      langLevel: ['', Validators.required],
      kompSkills: ['', Validators.required],
      kompLevel: ['', Validators.required],
      volunteersInterestArea: ['', Validators.required],
      items: this.fb.array([]),
    });
  }

  get items() {
    return this.filterForm.get('items') as FormArray;
  }

  addItem() {
    this.items.push(this.fb.control(''));
  }

  removeItem(index: number) {
    this.items.removeAt(index);
  }

  onSubmit() {
    // Handle form submission
    console.log(this.filterForm.value);
  }

  // getInnerObjectEntries() {
  //   return Object.entries(this.Volunteers.langSkills);
  // }
}
